server:
  port: ${PORT:8761}

eureka:
  client:
    service-url: ${EUREKAURL:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: rambling-eureka
